In [2]:
import numpy as np
from sklearn.model_selection import ParameterSampler
import json
from sklearn.model_selection import train_test_split

In [3]:
np.random.seed(0)
param_grid = {'dropout':[0.05, 0.1,0.2,0.3], 'learning_rate':[1.e-4,1.e-3,1.e-2,1.e-1]}
param_list = list(ParameterSampler(param_grid, n_iter=5))
print(param_list)
inp_dir='/users/nchernya/HHbbgg_ETH/bregression/notebooks/json/'
for i,item in enumerate(param_list):
    with open('%s/data_%i.json'%(inp_dir,i), 'w') as f:
        json.dump(item, f)


[{'learning_rate': 0.001, 'dropout': 0.05}, {'learning_rate': 0.01, 'dropout': 0.1}, {'learning_rate': 0.0001, 'dropout': 0.2}, {'learning_rate': 0.001, 'dropout': 0.2}, {'learning_rate': 0.001, 'dropout': 0.3}]


In [4]:
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X,y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] range(0, 5)


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=4)

In [6]:
print(X_train)
print(X_test)

[[2 3]
 [8 9]
 [4 5]]
[[0 1]
 [6 7]]


Now we would like to split in proper KFolds

In [24]:
from sklearn.model_selection import KFold
X = np.array([1, 2, 3, 4,5,6,7,8,9,10])
y = np.array([11, 21, 31, 41,51,61,71,81,91,101])
kf = KFold(n_splits=10,shuffle=True,random_state=98543)
#a = kf.get_n_splits(X)

idx = iter(kf.split(X))

for i in range(2):
    train_idx,test_idx = next(idx)
    print(i,train_idx,test_idx)
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    print(y_train,y_test)
    print('new')

0 [0 2 3 4 5 6 7 8 9] [1]
[ 11  31  41  51  61  71  81  91 101] [21]
new
1 [0 1 2 3 4 6 7 8 9] [5]
[ 11  21  31  41  51  71  81  91 101] [61]
new


In [25]:
import numpy as np
from sklearn.model_selection import ParameterSampler
import json

param_grid = {'dropout':[0.05, 0.1,0.2,0.3], 'optimizer_params':[dict(lr=1.e-03),dict(lr=0.5e-03)], 'layers':[[1024,512,256,128],[1024,512,256]] }
param_list = list(ParameterSampler(param_grid, n_iter=5))
print(param_list)
inp_dir='/users/nchernya/HHbbgg_ETH/bregression/notebooks/json/'
for i,item in enumerate(param_list):
    with open('%s/data_%i.json'%(inp_dir,i), 'w') as f:
        json.dump(item, f)


[{'layers': [1024, 512, 256], 'dropout': 0.2, 'optimizer_params': {'lr': 0.0005}}, {'layers': [1024, 512, 256, 128], 'dropout': 0.2, 'optimizer_params': {'lr': 0.001}}, {'layers': [1024, 512, 256, 128], 'dropout': 0.05, 'optimizer_params': {'lr': 0.0005}}, {'layers': [1024, 512, 256, 128], 'dropout': 0.1, 'optimizer_params': {'lr': 0.0005}}, {'layers': [1024, 512, 256], 'dropout': 0.1, 'optimizer_params': {'lr': 0.001}}]
